export const DEFAULT_ENRICH_MAX_ARTICLE_AGE_MONTHS = 6
export const DEFAULT_PUBLIC_RETENTION_MONTHS = 6

export const ARXIV_AI_SOURCE_KEY = 'arxiv-ai'
export const ARXIV_AI_ENRICH_MAX_ARTICLE_AGE_MONTHS = 5
export const ARXIV_AI_PUBLIC_RETENTION_MONTHS = 2
