#!/usr/bin/env npx tsx
import fs from 'node:fs'
import path from 'node:path'

type OutputItem = {
  enrichedArticleId: number
  primaryTagKeys: string[]
  adjacentTagKeys: string[]
}

type OutputFile = {
  items: OutputItem[]
}

function readArg(flag: string, fallback: string): string {
  const index = process.argv.indexOf(flag)
  if (index === -1 || index + 1 >= process.argv.length) return fallback
  return process.argv[index + 1]
}

function hasArg(flag: string): boolean {
  return process.argv.includes(flag)
}

function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function buildValues(
  rows: Array<{
    enrichedArticleId: number
    key: string
    sortOrder: number
    isPrimary?: boolean
  }>,
  includeIsPrimary: boolean,
): string {
  return rows
    .map((row) => {
      if (includeIsPrimary) {
        return `(${row.enrichedArticleId}, ${quote(row.key)}, ${row.sortOrder}, ${row.isPrimary ? 'true' : 'false'})`
      }
      return `(${row.enrichedArticleId}, ${quote(row.key)}, ${row.sortOrder})`
    })
    .join(',\n')
}

async function main(): Promise<void> {
  const rootDir = readArg('--root', path.join(process.cwd(), 'artifacts', 'ai-retag-all'))
  const outputsDir = path.join(rootDir, 'outputs')
  const outSqlDir = path.join(rootDir, 'sql')
  const phase = readArg('--phase', 'full') // full | primary-only
  const includeAdjacent = phase !== 'primary-only' && !hasArg('--primary-only')
  fs.mkdirSync(outSqlDir, { recursive: true })

  const outputFiles = fs.existsSync(outputsDir)
    ? fs.readdirSync(outputsDir).filter((file) => file.endsWith('.json')).sort()
    : []
  if (outputFiles.length === 0) {
    throw new Error(`No output files found: ${outputsDir}`)
  }

  const items: OutputItem[] = []
  for (const file of outputFiles) {
    const parsed = JSON.parse(fs.readFileSync(path.join(outputsDir, file), 'utf8')) as OutputFile
    for (const item of parsed.items ?? []) {
      items.push({
        enrichedArticleId: Number(item.enrichedArticleId),
        primaryTagKeys: (item.primaryTagKeys ?? []).slice(0, 5),
        adjacentTagKeys: (item.adjacentTagKeys ?? []).slice(0, 2),
      })
    }
  }

  const primaryRows = items.flatMap((item) =>
    item.primaryTagKeys.map((key, index) => ({
      enrichedArticleId: item.enrichedArticleId,
      key,
      sortOrder: index,
      isPrimary: index === 0,
    })),
  )
  const adjacentRows = includeAdjacent
    ? items.flatMap((item) =>
        item.adjacentTagKeys.map((key, index) => ({
          enrichedArticleId: item.enrichedArticleId,
          key,
          sortOrder: index,
        })),
      )
    : []

  const allEnrichedIds = [...new Set(items.map((item) => item.enrichedArticleId))].sort((a, b) => a - b)
  const deleteTargetValues = allEnrichedIds.map((id) => `(${id})`).join(',\n')
  const primaryValues = primaryRows.length > 0 ? buildValues(primaryRows, true) : ''
  const adjacentValues = adjacentRows.length > 0 ? buildValues(adjacentRows, false) : ''

  const sql = `-- generated by scripts/generate-ai-retag-sql.ts
-- phase=${phase}
-- includeAdjacent=${includeAdjacent}
-- totalItems=${items.length}

BEGIN;

CREATE TEMP TABLE tmp_ai_retag_targets (
  enriched_article_id bigint PRIMARY KEY
) ON COMMIT DROP;

INSERT INTO tmp_ai_retag_targets (enriched_article_id)
VALUES
${deleteTargetValues};

DELETE FROM articles_enriched_tags
WHERE enriched_article_id IN (SELECT enriched_article_id FROM tmp_ai_retag_targets);

${includeAdjacent ? `DELETE FROM articles_enriched_adjacent_tags
WHERE enriched_article_id IN (SELECT enriched_article_id FROM tmp_ai_retag_targets);` : '-- skip adjacent delete'}

${primaryRows.length > 0 ? `CREATE TEMP TABLE tmp_ai_primary_assignments (
  enriched_article_id bigint NOT NULL,
  tag_key text NOT NULL,
  sort_order int NOT NULL,
  is_primary boolean NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_ai_primary_assignments (enriched_article_id, tag_key, sort_order, is_primary)
VALUES
${primaryValues};

INSERT INTO articles_enriched_tags (enriched_article_id, tag_id, tag_source, is_primary)
SELECT
  p.enriched_article_id,
  tm.tag_id,
  'ai_retag',
  p.is_primary
FROM tmp_ai_primary_assignments p
JOIN tags_master tm ON tm.tag_key = p.tag_key
ON CONFLICT (enriched_article_id, tag_id) DO UPDATE
SET
  tag_source = EXCLUDED.tag_source,
  is_primary = EXCLUDED.is_primary;` : '-- no primary assignments'}

${includeAdjacent && adjacentRows.length > 0 ? `CREATE TEMP TABLE tmp_ai_adjacent_assignments (
  enriched_article_id bigint NOT NULL,
  adjacent_tag_key text NOT NULL,
  sort_order int NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_ai_adjacent_assignments (enriched_article_id, adjacent_tag_key, sort_order)
VALUES
${adjacentValues};

INSERT INTO articles_enriched_adjacent_tags (enriched_article_id, adjacent_tag_id, sort_order)
SELECT
  a.enriched_article_id,
  atm.adjacent_tag_id,
  a.sort_order
FROM tmp_ai_adjacent_assignments a
JOIN adjacent_tags_master atm ON atm.tag_key = a.adjacent_tag_key
ON CONFLICT (enriched_article_id, adjacent_tag_id) DO UPDATE
SET sort_order = EXCLUDED.sort_order;` : '-- no adjacent assignments or primary-only phase'}

-- L4 tags sync
DELETE FROM public_article_tags
WHERE public_article_id IN (
  SELECT pa.public_article_id
  FROM public_articles pa
  JOIN tmp_ai_retag_targets t ON t.enriched_article_id = pa.enriched_article_id
);

INSERT INTO public_article_tags (public_article_id, tag_id, sort_order)
SELECT
  pa.public_article_id,
  aet.tag_id,
  ROW_NUMBER() OVER (
    PARTITION BY pa.public_article_id
    ORDER BY aet.is_primary DESC, aet.tag_id
  )::int - 1
FROM public_articles pa
JOIN tmp_ai_retag_targets t ON t.enriched_article_id = pa.enriched_article_id
JOIN articles_enriched_tags aet ON aet.enriched_article_id = pa.enriched_article_id;

${includeAdjacent ? `DELETE FROM public_article_adjacent_tags
WHERE public_article_id IN (
  SELECT pa.public_article_id
  FROM public_articles pa
  JOIN tmp_ai_retag_targets t ON t.enriched_article_id = pa.enriched_article_id
);

INSERT INTO public_article_adjacent_tags (public_article_id, adjacent_tag_id, sort_order)
SELECT
  pa.public_article_id,
  aeat.adjacent_tag_id,
  aeat.sort_order
FROM public_articles pa
JOIN tmp_ai_retag_targets t ON t.enriched_article_id = pa.enriched_article_id
JOIN articles_enriched_adjacent_tags aeat ON aeat.enriched_article_id = pa.enriched_article_id;` : '-- skip L4 adjacent sync'}

COMMIT;
`

  const filename =
    phase === 'primary-only'
      ? 'ai-retag-phase2-primary-only.sql'
      : 'ai-retag-phase1-full.sql'
  const outputPath = path.join(outSqlDir, filename)
  fs.writeFileSync(outputPath, sql, 'utf8')

  console.log(`outputPath=${outputPath}`)
  console.log(`items=${items.length}`)
  console.log(`primaryAssignments=${primaryRows.length}`)
  console.log(`adjacentAssignments=${adjacentRows.length}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
