import fs from 'node:fs'
import path from 'node:path'

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }

type InputFile = {
  items: Array<{
    rawArticleId: number
  }>
}

type OutputFile = {
  items: Array<{
    rawArticleId: number | string
  }>
}

function readJson<T>(filePath: string): T {
  const raw = fs.readFileSync(filePath, 'utf8').replace(/^\uFEFF/, '')
  return JSON.parse(raw) as T
}

function buildDollarQuoteTag(label: string, payload: string): string {
  let tag = `$${label}$`
  let suffix = 1

  while (payload.includes(tag)) {
    tag = `$${label}_${suffix}$`
    suffix += 1
  }

  return tag
}

function embedJson(label: string, value: JsonValue): string {
  const payload = JSON.stringify(value)
  const tag = buildDollarQuoteTag(label, payload)
  return `${tag}${payload}${tag}::jsonb`
}

function normalizeRawArticleId(value: number | string): number {
  const normalized = typeof value === 'number' ? value : Number(value)
  if (!Number.isInteger(normalized) || normalized <= 0) {
    throw new Error(`Invalid rawArticleId: ${String(value)}`)
  }
  return normalized
}

function main(): void {
  const baseDir =
    process.argv[2] ??
    path.join(process.cwd(), 'artifact', 'gemini-cli-enrich-backlog-1500')
  const inputsDir = path.join(baseDir, 'inputs')
  const outputsDir = path.join(baseDir, 'outputs')
  const sqlDir = path.join(baseDir, 'sql')
  const outputSqlPath = path.join(sqlDir, 'manual-gemini-enrich-import.sql')

  const inputRows: string[] = []
  const outputRows: string[] = []
  let totalItems = 0

  for (let part = 1; part <= 8; part += 1) {
    const partLabel = String(part).padStart(3, '0')
    const inputPath = path.join(inputsDir, `ai-enrich-inputs-part-${partLabel}.json`)
    const outputPath = path.join(outputsDir, `ai-enrich-outputs-part-${partLabel}.json`)

    if (!fs.existsSync(inputPath)) {
      throw new Error(`Missing input file: ${inputPath}`)
    }
    if (!fs.existsSync(outputPath)) {
      throw new Error(`Missing output file: ${outputPath}`)
    }

    const inputFile = readJson<InputFile>(inputPath)
    const outputFile = readJson<OutputFile>(outputPath)

    if (inputFile.items.length !== outputFile.items.length) {
      throw new Error(
        `Part ${partLabel} count mismatch: input=${inputFile.items.length} output=${outputFile.items.length}`,
      )
    }

    const inputIds = inputFile.items.map((item) => normalizeRawArticleId(item.rawArticleId))
    const outputIds = outputFile.items.map((item) => normalizeRawArticleId(item.rawArticleId))

    const missingOutputIds = inputIds.filter((id) => !outputIds.includes(id))
    if (missingOutputIds.length > 0) {
      throw new Error(
        `Part ${partLabel} missing output raw IDs: ${missingOutputIds.slice(0, 10).join(', ')}`,
      )
    }

    totalItems += inputFile.items.length
    inputRows.push(`(${part}, ${embedJson(`part_${partLabel}_input`, inputFile as JsonValue)})`)
    outputRows.push(`(${part}, ${embedJson(`part_${partLabel}_output`, outputFile as JsonValue)})`)
  }

  const sql = `-- Generated by scripts/generate-manual-gemini-enrich-sql.ts
-- Source: artifact/gemini-cli-enrich-backlog-1500/inputs + outputs
-- Generated at: ${new Date().toISOString()}
-- Expected import count: ${totalItems}

BEGIN;

CREATE TEMP TABLE manual_gemini_input_files (
  part_no integer PRIMARY KEY,
  payload jsonb NOT NULL
) ON COMMIT DROP;

CREATE TEMP TABLE manual_gemini_output_files (
  part_no integer PRIMARY KEY,
  payload jsonb NOT NULL
) ON COMMIT DROP;

INSERT INTO manual_gemini_input_files (part_no, payload)
VALUES
${inputRows.join(',\n')};

INSERT INTO manual_gemini_output_files (part_no, payload)
VALUES
${outputRows.join(',\n')};

CREATE TEMP TABLE manual_gemini_inputs AS
SELECT
  mif.part_no,
  (item->>'rawArticleId')::bigint AS raw_article_id,
  item->>'sourceTargetId' AS source_target_id,
  item->>'sourceCategory' AS source_category,
  item->>'sourceType' AS source_type,
  item->>'sourceKey' AS source_key,
  item->>'normalizedUrl' AS normalized_url,
  NULLIF(item->>'citedUrl', '') AS cited_url,
  item->>'canonicalUrl' AS canonical_url,
  NULLIF(item->>'sourceUpdatedAt', '') AS source_updated_at_text,
  item->>'summaryBasis' AS summary_basis,
  item->>'contentPath' AS content_path,
  item->'provisionalBase' AS provisional_base,
  item->>'dedupeStatus' AS dedupe_status,
  NULLIF(item->>'dedupeGroupKey', '') AS dedupe_group_key,
  COALESCE((item->>'isRelevant')::boolean, false) AS is_relevant,
  COALESCE(item->'matchedTagIds', '[]'::jsonb) AS matched_tag_ids,
  COALESCE(item->'candidateTags', '[]'::jsonb) AS candidate_tags,
  item->>'publicationBasisIfSummaryExists' AS publication_basis_if_summary_exists
FROM manual_gemini_input_files mif
CROSS JOIN LATERAL jsonb_array_elements(mif.payload->'items') AS item;

CREATE TEMP TABLE manual_gemini_outputs AS
SELECT
  mof.part_no,
  (item->>'rawArticleId')::bigint AS raw_article_id,
  item->>'titleJa' AS title_ja,
  item->>'summary100Ja' AS summary_100_ja,
  item->>'summary200Ja' AS summary_200_ja,
  COALESCE(item->'matchedTagKeys', '[]'::jsonb) AS matched_tag_keys,
  COALESCE(item->'proposedTags', '[]'::jsonb) AS proposed_tags
FROM manual_gemini_output_files mof
CROSS JOIN LATERAL jsonb_array_elements(mof.payload->'items') AS item;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM (
      SELECT part_no, COUNT(*) AS input_count
      FROM manual_gemini_inputs
      GROUP BY part_no
    ) i
    FULL OUTER JOIN (
      SELECT part_no, COUNT(*) AS output_count
      FROM manual_gemini_outputs
      GROUP BY part_no
    ) o USING (part_no)
    WHERE COALESCE(i.input_count, 0) <> COALESCE(o.output_count, 0)
  ) THEN
    RAISE EXCEPTION 'manual Gemini import aborted: input/output count mismatch by part';
  END IF;

  IF EXISTS (
    SELECT raw_article_id
    FROM manual_gemini_inputs
    GROUP BY raw_article_id
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'manual Gemini import aborted: duplicate raw_article_id in inputs';
  END IF;

  IF EXISTS (
    SELECT raw_article_id
    FROM manual_gemini_outputs
    GROUP BY raw_article_id
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'manual Gemini import aborted: duplicate raw_article_id in outputs';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM manual_gemini_inputs i
    LEFT JOIN manual_gemini_outputs o
      ON o.part_no = i.part_no
     AND o.raw_article_id = i.raw_article_id
    WHERE o.raw_article_id IS NULL
  ) THEN
    RAISE EXCEPTION 'manual Gemini import aborted: some raw_article_id values are missing outputs';
  END IF;
END $$;

CREATE TEMP TABLE manual_gemini_raw_context AS
SELECT
  i.part_no,
  i.raw_article_id,
  ar.source_target_id AS db_source_target_id,
  ar.normalized_url AS db_normalized_url,
  COALESCE(st.source_category, 'unknown') AS db_source_category,
  COALESCE(st.source_type, 'news') AS db_source_type,
  st.content_language AS db_content_language,
  CASE
    WHEN COALESCE(st.commercial_use_policy, 'permitted') = 'prohibited'
      OR od.commercial_use_policy = 'prohibited'
      THEN 'prohibited'
    ELSE COALESCE(st.commercial_use_policy, 'permitted')
  END AS commercial_use_policy
FROM manual_gemini_inputs i
JOIN articles_raw ar
  ON ar.raw_article_id = i.raw_article_id
JOIN source_targets st
  ON st.source_target_id = ar.source_target_id
LEFT JOIN observed_article_domains od
  ON od.domain = lower(
    regexp_replace(
      split_part(
        split_part(coalesce(ar.cited_url, ar.source_url, ar.normalized_url), '://', 2),
        '/',
        1
      ),
      '^www\\.',
      ''
    )
  );

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM manual_gemini_inputs i
    LEFT JOIN manual_gemini_raw_context rc
      ON rc.part_no = i.part_no
     AND rc.raw_article_id = i.raw_article_id
    WHERE rc.raw_article_id IS NULL
  ) THEN
    RAISE EXCEPTION 'manual Gemini import aborted: some raw_article_id values do not exist in articles_raw';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM manual_gemini_inputs i
    JOIN manual_gemini_raw_context rc
      ON rc.part_no = i.part_no
     AND rc.raw_article_id = i.raw_article_id
    WHERE rc.db_source_target_id::text <> i.source_target_id
       OR rc.db_normalized_url <> i.normalized_url
  ) THEN
    RAISE EXCEPTION 'manual Gemini import aborted: input JSON no longer matches current articles_raw snapshot';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM manual_gemini_outputs o
    CROSS JOIN LATERAL jsonb_array_elements_text(o.matched_tag_keys) AS k(tag_key)
    LEFT JOIN tags_master tm ON tm.tag_key = k.tag_key
    WHERE tm.tag_id IS NULL
  ) THEN
    RAISE EXCEPTION 'manual Gemini import aborted: unknown matchedTagKeys detected';
  END IF;
END $$;

CREATE TEMP TABLE manual_gemini_resolved AS
WITH resolved_base AS (
  SELECT
    i.part_no,
    i.raw_article_id,
    i.source_target_id,
    COALESCE(NULLIF(i.source_category, ''), rc.db_source_category) AS source_category,
    COALESCE(NULLIF(i.source_type, ''), rc.db_source_type) AS source_type,
    i.source_key,
    i.normalized_url,
    i.cited_url,
    i.canonical_url,
    i.source_updated_at_text,
    CASE
      WHEN o.title_ja IS NULL THEN NULL
      ELSE left(regexp_replace(trim(o.title_ja), '\\s+', ' ', 'g'), 200)
    END AS title_ja,
    CASE
      WHEN o.summary_100_ja IS NULL THEN NULL
      ELSE left(regexp_replace(trim(o.summary_100_ja), '\\s+', ' ', 'g'), 100)
    END AS summary_100_ja,
    CASE
      WHEN o.summary_200_ja IS NULL THEN NULL
      ELSE left(regexp_replace(trim(o.summary_200_ja), '\\s+', ' ', 'g'), 200)
    END AS summary_200_ja,
    i.summary_basis,
    i.content_path,
    COALESCE((i.provisional_base->>'isProvisional')::boolean, false) AS provisional_base_is_provisional,
    NULLIF(i.provisional_base->>'provisionalReason', '') AS provisional_base_reason,
    i.dedupe_status,
    i.dedupe_group_key,
    i.is_relevant,
    i.matched_tag_ids AS input_matched_tag_ids,
    i.candidate_tags AS input_candidate_tags,
    i.publication_basis_if_summary_exists,
    rc.db_content_language AS content_language,
    rc.commercial_use_policy,
    o.matched_tag_keys,
    o.proposed_tags
  FROM manual_gemini_inputs i
  JOIN manual_gemini_outputs o
    ON o.part_no = i.part_no
   AND o.raw_article_id = i.raw_article_id
  JOIN manual_gemini_raw_context rc
    ON rc.part_no = i.part_no
   AND rc.raw_article_id = i.raw_article_id
),
resolved_tags AS (
  SELECT
    rb.*,
    CASE
      WHEN jsonb_typeof(rb.matched_tag_keys) = 'array' AND jsonb_array_length(rb.matched_tag_keys) > 0 THEN (
        SELECT COALESCE(jsonb_agg(to_jsonb(tm.tag_id) ORDER BY mk.ord), '[]'::jsonb)
        FROM jsonb_array_elements_text(rb.matched_tag_keys) WITH ORDINALITY AS mk(tag_key, ord)
        JOIN tags_master tm
          ON tm.tag_key = mk.tag_key
      )
      ELSE COALESCE(rb.input_matched_tag_ids, '[]'::jsonb)
    END AS matched_tag_ids_json,
    CASE
      WHEN jsonb_typeof(rb.proposed_tags) = 'array' AND jsonb_array_length(rb.proposed_tags) > 0 THEN (
        SELECT COALESCE(
          jsonb_agg(
            jsonb_build_object(
              'candidate_key', proposed_tag,
              'display_name', proposed_tag
            )
            ORDER BY ord
          ),
          '[]'::jsonb
        )
        FROM jsonb_array_elements_text(rb.proposed_tags) WITH ORDINALITY AS p(proposed_tag, ord)
      )
      ELSE (
        SELECT COALESCE(
          jsonb_agg(
            jsonb_build_object(
              'candidate_key', candidate_item->>'candidateKey',
              'display_name', candidate_item->>'displayName'
            )
          ),
          '[]'::jsonb
        )
        FROM jsonb_array_elements(COALESCE(rb.input_candidate_tags, '[]'::jsonb)) AS candidate_item
      )
    END AS candidate_tags_json
  FROM resolved_base rb
)
SELECT
  rt.part_no,
  rt.raw_article_id,
  rt.source_target_id,
  rt.source_category,
  rt.source_type,
  rt.source_key,
  rt.normalized_url,
  rt.cited_url,
  rt.canonical_url,
  rt.source_updated_at_text AS source_updated_at,
  rt.title_ja AS title,
  rt.summary_100_ja AS summary_100,
  rt.summary_200_ja AS summary_200,
  rt.summary_basis,
  rt.content_path,
  CASE
    WHEN rt.publication_basis_if_summary_exists = 'source_snippet' THEN false
    ELSE rt.provisional_base_is_provisional
  END AS is_provisional,
  CASE
    WHEN rt.publication_basis_if_summary_exists = 'source_snippet' THEN NULL
    ELSE rt.provisional_base_reason
  END AS provisional_reason,
  rt.dedupe_status,
  rt.dedupe_group_key,
  rt.publication_basis_if_summary_exists AS publication_basis,
  CASE
    WHEN rt.publication_basis_if_summary_exists = 'hold' THEN NULL
    ELSE COALESCE(NULLIF(rt.summary_200_ja, ''), NULLIF(rt.summary_100_ja, ''))
  END AS publication_text,
  CASE
    WHEN rt.publication_basis_if_summary_exists <> 'hold'
      AND rt.dedupe_status = 'unique'
      AND rt.is_relevant
      THEN true
    ELSE false
  END AS publish_candidate,
  CASE
    WHEN rt.content_path = 'full' THEN 'full_content'
    WHEN rt.publication_basis_if_summary_exists = 'source_snippet' THEN 'source_snippet'
    ELSE 'title_only'
  END AS summary_input_basis,
  rt.content_language,
  rt.commercial_use_policy,
  rt.matched_tag_ids_json,
  rt.candidate_tags_json,
  GREATEST(
    0,
    LEAST(
      100,
      CASE WHEN rt.content_path = 'full' THEN 70 ELSE 45 END
      + (SELECT COUNT(*) * 8 FROM jsonb_array_elements_text(rt.matched_tag_ids_json))
      + 6
      + CASE WHEN rt.is_relevant THEN 0 ELSE -25 END
    )
  ) AS score,
  CASE
    WHEN rt.content_path = 'full'
      THEN
        CASE
          WHEN rt.is_relevant
            THEN format(
              'full extraction, %s matched tags, manual_cli summary',
              (SELECT COUNT(*) FROM jsonb_array_elements_text(rt.matched_tag_ids_json))
            )
          ELSE format(
            'full extraction, %s matched tags, manual_cli summary; low source relevance',
            (SELECT COUNT(*) FROM jsonb_array_elements_text(rt.matched_tag_ids_json))
          )
        END
    ELSE
      CASE
        WHEN rt.is_relevant
          THEN format(
            'snippet fallback, %s matched tags, manual_cli summary',
            (SELECT COUNT(*) FROM jsonb_array_elements_text(rt.matched_tag_ids_json))
          )
        ELSE format(
          'snippet fallback, %s matched tags, manual_cli summary; low source relevance',
          (SELECT COUNT(*) FROM jsonb_array_elements_text(rt.matched_tag_ids_json))
        )
      END
  END AS score_reason,
  NULL::text AS thumbnail_url,
  rt.summary_100_ja AS detail_summary_100_for_check,
  rt.summary_200_ja AS detail_summary_200_for_check
FROM resolved_tags rt;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM manual_gemini_resolved
    WHERE NULLIF(title, '') IS NULL
       OR NULLIF(summary_100, '') IS NULL
       OR NULLIF(summary_200, '') IS NULL
  ) THEN
    RAISE EXCEPTION 'manual Gemini import aborted: empty title/summary after normalization';
  END IF;
END $$;

CREATE TEMP TABLE manual_gemini_existing AS
SELECT DISTINCT ON (r.raw_article_id)
  r.raw_article_id,
  ae.enriched_article_id
FROM manual_gemini_resolved r
JOIN articles_enriched ae
  ON ae.raw_article_id = r.raw_article_id
  OR ae.normalized_url = r.normalized_url
ORDER BY
  r.raw_article_id,
  CASE WHEN ae.raw_article_id = r.raw_article_id THEN 0 ELSE 1 END,
  ae.processed_at DESC,
  ae.enriched_article_id DESC;

INSERT INTO articles_enriched_history (
  enriched_article_id, raw_article_id, source_target_id, normalized_url, cited_url, canonical_url,
  content_language, title, thumbnail_url, summary_100, summary_200, summary_basis, content_path, is_provisional,
  provisional_reason, dedupe_status, dedupe_group_key, publish_candidate, publication_basis,
  publication_text, summary_input_basis, score, score_reason, ai_processing_state, source_updated_at, topic_group_id,
  summary_embedding, embedding_model, embedding_updated_at, processed_at, created_at, updated_at, commercial_use_policy
)
SELECT
  ae.enriched_article_id, ae.raw_article_id, ae.source_target_id, ae.normalized_url, ae.cited_url, ae.canonical_url,
  ae.content_language, ae.title, ae.thumbnail_url, ae.summary_100, ae.summary_200, ae.summary_basis, ae.content_path, ae.is_provisional,
  ae.provisional_reason, ae.dedupe_status, ae.dedupe_group_key, ae.publish_candidate, ae.publication_basis,
  ae.publication_text, ae.summary_input_basis, ae.score, ae.score_reason, ae.ai_processing_state, ae.source_updated_at, ae.topic_group_id,
  ae.summary_embedding, ae.embedding_model, ae.embedding_updated_at, ae.processed_at, ae.created_at, ae.updated_at, ae.commercial_use_policy
FROM articles_enriched ae
JOIN manual_gemini_existing me
  ON me.enriched_article_id = ae.enriched_article_id;

UPDATE articles_enriched ae
SET
  raw_article_id = r.raw_article_id,
  source_target_id = r.source_target_id::uuid,
  source_category = r.source_category,
  source_type = r.source_type,
  content_language = r.content_language,
  cited_url = r.cited_url,
  canonical_url = r.canonical_url,
  title = r.title,
  thumbnail_url = r.thumbnail_url,
  summary_100 = r.summary_100,
  summary_200 = r.summary_200,
  summary_basis = r.summary_basis,
  content_path = r.content_path,
  is_provisional = r.is_provisional,
  provisional_reason = r.provisional_reason,
  dedupe_status = r.dedupe_status,
  dedupe_group_key = r.dedupe_group_key,
  publish_candidate = r.publish_candidate,
  publication_basis = r.publication_basis,
  publication_text = r.publication_text,
  summary_input_basis = r.summary_input_basis,
  score = r.score,
  score_reason = r.score_reason,
  ai_processing_state = 'completed',
  commercial_use_policy = r.commercial_use_policy,
  source_updated_at = NULLIF(r.source_updated_at::text, '')::timestamptz,
  topic_group_id = NULL,
  summary_embedding = NULL,
  embedding_model = NULL,
  processed_at = now(),
  updated_at = now()
FROM manual_gemini_resolved r
JOIN manual_gemini_existing me
  ON me.raw_article_id = r.raw_article_id
WHERE ae.enriched_article_id = me.enriched_article_id;

INSERT INTO articles_enriched (
  raw_article_id, source_target_id, source_category, source_type, normalized_url, cited_url,
  canonical_url, title, thumbnail_url, summary_100, summary_200, summary_basis, content_path, is_provisional,
  provisional_reason, dedupe_status, dedupe_group_key, publish_candidate, publication_basis,
  publication_text, summary_input_basis, score, score_reason, ai_processing_state, source_updated_at,
  content_language, topic_group_id, summary_embedding, embedding_model, embedding_updated_at, commercial_use_policy
)
SELECT
  r.raw_article_id,
  r.source_target_id::uuid,
  r.source_category,
  r.source_type,
  r.normalized_url,
  r.cited_url,
  r.canonical_url,
  r.title,
  r.thumbnail_url,
  r.summary_100,
  r.summary_200,
  r.summary_basis,
  r.content_path,
  r.is_provisional,
  r.provisional_reason,
  r.dedupe_status,
  r.dedupe_group_key,
  r.publish_candidate,
  r.publication_basis,
  r.publication_text,
  r.summary_input_basis,
  r.score,
  r.score_reason,
  'completed',
  NULLIF(r.source_updated_at::text, '')::timestamptz,
  r.content_language,
  NULL,
  NULL,
  NULL,
  NULL,
  r.commercial_use_policy
FROM manual_gemini_resolved r
LEFT JOIN manual_gemini_existing me
  ON me.raw_article_id = r.raw_article_id
WHERE me.raw_article_id IS NULL;

CREATE TEMP TABLE manual_gemini_upserted AS
SELECT
  r.*,
  ae.enriched_article_id
FROM manual_gemini_resolved r
JOIN LATERAL (
  SELECT enriched_article_id
  FROM articles_enriched ae
  WHERE ae.raw_article_id = r.raw_article_id
     OR ae.normalized_url = r.normalized_url
  ORDER BY
    CASE WHEN ae.raw_article_id = r.raw_article_id THEN 0 ELSE 1 END,
    ae.processed_at DESC,
    ae.enriched_article_id DESC
  LIMIT 1
) ae ON true;

DELETE FROM articles_enriched_sources aes
USING manual_gemini_upserted u
WHERE aes.enriched_article_id = u.enriched_article_id;

INSERT INTO articles_enriched_sources (
  enriched_article_id,
  source_target_id,
  source_key,
  source_display_name,
  source_category,
  source_type,
  selection_status,
  selection_reason,
  similarity_score
)
SELECT
  source_rows.enriched_article_id,
  source_rows.source_target_id,
  source_rows.source_key,
  source_rows.source_display_name,
  source_rows.source_category,
  source_rows.source_type,
  source_rows.selection_status,
  source_rows.selection_reason,
  source_rows.similarity_score
FROM (
  SELECT DISTINCT ON (u.enriched_article_id, u.source_key, CASE WHEN u.dedupe_status = 'unique' THEN 'selected' ELSE 'rejected' END)
    u.enriched_article_id,
    u.source_target_id::uuid AS source_target_id,
    u.source_key,
    u.source_key AS source_display_name,
    u.source_category,
    u.source_type,
    CASE WHEN u.dedupe_status = 'unique' THEN 'selected' ELSE 'rejected' END AS selection_status,
    CASE WHEN u.dedupe_status = 'unique' THEN 'primary article source' ELSE 'dedupe group member' END AS selection_reason,
    NULL::numeric AS similarity_score
  FROM manual_gemini_upserted u
  ORDER BY
    u.enriched_article_id,
    u.source_key,
    CASE WHEN u.dedupe_status = 'unique' THEN 'selected' ELSE 'rejected' END,
    u.raw_article_id DESC
) source_rows
ON CONFLICT (enriched_article_id, source_key, selection_status) DO UPDATE SET
  source_target_id = EXCLUDED.source_target_id,
  source_display_name = EXCLUDED.source_display_name,
  source_category = EXCLUDED.source_category,
  source_type = EXCLUDED.source_type,
  selection_reason = EXCLUDED.selection_reason,
  similarity_score = EXCLUDED.similarity_score,
  updated_at = now();

DELETE FROM articles_enriched_tags aet
USING manual_gemini_upserted u
WHERE aet.enriched_article_id = u.enriched_article_id;

INSERT INTO articles_enriched_tags (enriched_article_id, tag_id, tag_source, is_primary)
SELECT
  tag_rows.enriched_article_id,
  tag_rows.tag_id,
  'master',
  tag_rows.min_ord = 1
FROM (
  SELECT
    u.enriched_article_id,
    tag_value.tag_id::uuid AS tag_id,
    MIN(tag_value.ord) AS min_ord
  FROM manual_gemini_upserted u
  CROSS JOIN LATERAL jsonb_array_elements_text(u.matched_tag_ids_json) WITH ORDINALITY AS tag_value(tag_id, ord)
  GROUP BY u.enriched_article_id, tag_value.tag_id::uuid
) tag_rows;

INSERT INTO tag_candidate_pool (candidate_key, display_name, latest_origin_raw_id, review_status)
SELECT
  candidate.candidate_key,
  MIN(candidate.display_name) AS display_name,
  MAX(u.raw_article_id) AS latest_origin_raw_id,
  'candidate'
FROM manual_gemini_upserted u
CROSS JOIN LATERAL jsonb_to_recordset(u.candidate_tags_json) AS candidate(candidate_key text, display_name text)
WHERE NULLIF(candidate.candidate_key, '') IS NOT NULL
GROUP BY candidate.candidate_key
ON CONFLICT (candidate_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  latest_origin_raw_id = EXCLUDED.latest_origin_raw_id,
  seen_count = tag_candidate_pool.seen_count + 1,
  last_seen_at = now(),
  updated_at = now();

UPDATE articles_raw ar
SET
  is_processed = true,
  has_source_update = false,
  process_after = now(),
  last_error = NULL,
  updated_at = now()
FROM manual_gemini_resolved r
WHERE ar.raw_article_id = r.raw_article_id;

UPDATE tags_master tm
SET
  article_count = COALESCE(counts.article_count, 0),
  last_seen_at = CASE WHEN COALESCE(counts.article_count, 0) > 0 THEN now() ELSE tm.last_seen_at END,
  updated_at = now()
FROM (
  SELECT aet.tag_id, COUNT(*)::integer AS article_count
  FROM articles_enriched_tags aet
  GROUP BY aet.tag_id
) counts
WHERE tm.tag_id = counts.tag_id;

UPDATE tags_master
SET article_count = 0, updated_at = now()
WHERE tag_id NOT IN (SELECT DISTINCT tag_id FROM articles_enriched_tags)
  AND article_count <> 0;

DO $$
DECLARE
  expected_count integer;
  processed_count integer;
BEGIN
  SELECT COUNT(*) INTO expected_count FROM manual_gemini_resolved;
  SELECT COUNT(*) INTO processed_count
  FROM articles_raw ar
  JOIN manual_gemini_resolved r
    ON r.raw_article_id = ar.raw_article_id
  WHERE ar.is_processed = true;

  IF expected_count <> processed_count THEN
    RAISE EXCEPTION 'manual Gemini import aborted: processed raw count mismatch (% vs %)', processed_count, expected_count;
  END IF;
END $$;

COMMIT;
`

  fs.mkdirSync(sqlDir, { recursive: true })
  fs.writeFileSync(outputSqlPath, sql, 'utf8')
  console.log(`sql=${outputSqlPath}`)
  console.log(`items=${totalItems}`)
}

main()
